site_name: Vox
nav:
- Home: index.md
- Installing: install.md
- Getting started: get_started.md
- STL objects: stl.md 
- Interpolation: interpolation.md
- Documentation:
  - Bone class methods: bone_docs.md
  - Functions: func_docs.md

theme: bootstrap 