site_name: PCA-2
nav:
- Home: index.md
- Installing: install.md
- Getting started: get_started.md
- STL objects: stl.md 
- Interpolation: interpolation.md
- Documentation: documentation.md
  # - Bone class methods: bone_docs.md
  # - Functions: func_docs.md

theme: readthedocs
